global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['microblog:1323']
  - job_name: golang
    metrics_path: /metrics
    static_configs:
      - targets:
          - golang:1323